services:
  - type: web
    name: dvys-ai
    env: php
    plan: free
    buildCommand: "composer install --no-dev"
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: BASE_URL
        fromService:
          name: dvys-ai
          type: web
          property: hostport
